### ISSUE TITLE
Game mode to make two bots play against each them?

### ISSUE THREAD

**Issue by MxtAppz** [dulvui/pocket-broomball#12]
Is this feature already there? If not, could it be implemented (with selectable difficulty for each bot)? Thanks in advanced.

**Comment by dulvui** [comment]
Thank you very much for your suggestion!
It's not a feature yet, but would be implemented quite easy. Would be interesting to see playing bots against each other :)
In which game mode would you like to see this? Just simple 1vs1 with computer vs computer and changeable difficulty or in championship mode?

**Comment by MxtAppz** [comment]
> Thank you very much for your suggestion! It's not a feature yet, but would be implemented quite easy. Would be interesting to see playing bots against each other :) In which game mode would you like to see this? Just simple 1vs1 with computer vs computer and changeable difficulty or in championship mode?

Preferably in 1vs1, but if it isn't too much work for you it would be nice to make it for both modes. Thanks for your time!!!

**Comment by dulvui** [comment]
Okay I'll add it to the 1vs1 and then see how much effort it would be for the other mode.

**Comment by dulvui** [comment]
I created now a new version with bot vs bot mode in single mode: Play -> Bot vs Bot.
Its already playable on itch.io https://simondalvai.itch.io/pocket-broomball

I will add the possibility to adjust the difficulty of each bot in a future release, since I will refactor other parts of the code, including the difficulty section. Then I'll add also the possibility to "simulate" matches in championship mode, where  a bot will play for you.

**Comment by dulvui** [comment]
I fixed some Bugs in the latest updates regarding Bot vs Bot mode.
There is another open issue #26 for the difficulty selection, so I'll close this issue and write about updates in that issue.
