### ISSUE TITLE
Have a Github milestones / Roadmap

### ISSUE THREAD

**Issue by RustoMCSpit** [dulvui/pocket-broomball#22]

**Comment by dulvui** [comment]
Nice idea! I'll create a project in this repository and assign the issued to the corresponding row right?

**Comment by RustoMCSpit** [comment]
> Nice idea! I'll create a project in this repository and assign the issued to the corresponding row right?

yeah basically, check out these examples https://github.com/zyrouge/symphony/milestones
https://github.com/godotengine/godot/milestones

**Comment by RustoMCSpit** [comment]
any update?

**Comment by dulvui** [comment]
I checked now how milestones work, but for now I won't work with milestones.
On reason is that they are Github specific, and I try to remain platform neutral as possible, since I have also clones of all my repos on Codeberg. Second reason is that I work on the game when I have time,s o defining a date to a specific milestone doesn't work for me.

But a roadmap could make more sense and I'll check what options exist, probably a simple roadmap.md file.

**Comment by RustoMCSpit** [comment]
> But a roadmap could make more sense and I'll check what options exist, probably a simple roadmap.md file.

okay cool, looking forwqrd to it

**Comment by dulvui** [comment]
I won't create a roadmap for now. If I change my mind, I'll update this issue

**Comment by dulvui** [comment]
I have created now a roadmap
https://github.com/dulvui/pocket-broomball/blob/main/ROADMAP.md
